### ISSUE TITLE
not clear if combining characters are supposed to be supported

### ISSUE THREAD

**Issue by timo** [tbrowder/perl6-read-write-tests#2]
Hey,

Perl 6 goes to great lengths to make sure advanced unicode stuff gets supported properly.

If we're allowed to get wrong results like perl5 would, or perhaps even like wc -l might, we'd be able to be a lot faster than we are right now. I'll whip up a version of the benchmark that does that later today to figure out how much faster we can go.

**Comment by timo** [comment]
sorry, i got distracted by trying to figure out why the "slurp" method is so slow. turns out it spends about a quarter of its total time in GC, marking all the entries in the gigantic array ... Couldn't make that much faster yet :(

**Comment by tbrowder** [comment]
Would be nice if there were a way to turn off GC if desired.

**Comment by tbrowder** [comment]
If the unicode handling is truly slowing things down versus Perl, then maybe there ought to be some user-controlled way to turn off unicode as well as GC.

**Comment by tbrowder** [comment]
Timo, today I modified the Perl 6 reader to open the file in ascii encoding but haven't seen any significant speed gain.  What else did you have in mind?

**Comment by tbrowder** [comment]
README mentions this is an ASCII test
