### ISSUE TITLE
scripts look for "-gb-" files instead of "-Gb-" and fails on linux

### ISSUE THREAD

**Issue by timo** [tbrowder/perl6-read-write-tests#3]
just needs a change in run-rw-tests where a single instance of -gb- makes things fail.

**Comment by timo** [comment]
bin/run-rw-test.p6 also has this issue.

**Comment by tbrowder** [comment]
thanks, will fix

**Comment by tbrowder** [comment]
major clean up--try it now

**Comment by tbrowder** [comment]
fixed

**Comment by tbrowder** [comment]
On Sat, Oct 22, 2016 at 11:31 AM, timo <notifications@github.com> wrote:
> just needs a change in run-rw-tests where a single instance of -gb- makes
> things fail.

Thanks, still cleaning up.  I filed issue too early while github was
acting up and I didn't have
the complete picture.
